/**
 * The Jesus Festival blog.
 *
 * These are statically prerendered pages (unlike the in-app newsfeed, which is
 * client-rendered from Supabase and therefore invisible to crawlers). Each post
 * is real, useful writing that links out to the wider Kingdom Network where it
 * genuinely helps the reader — which is also exactly what earns SEO value.
 *
 * Inline links use a tiny [label](url) syntax rendered as real <a> elements —
 * never dangerouslySetInnerHTML.
 */

export type Block =
  | { t: "p"; text: string }
  | { t: "h2"; text: string }
  | { t: "list"; items: string[] }
  | { t: "quote"; text: string; ref: string };

export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  emoji: string;
  date: string;
  readMins: number;
  body: Block[];
  faqs?: { question: string; answer: string }[];
  sources?: { name: string; url: string }[];
  /** Domains from KINGDOM_SITES to surface as cards at the end of the post. */
  related: string[];
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "jesus-festival-starts-tomorrow-final-checklist",
    title: "Jesus Festival Starts Tomorrow: Your Final Gage Park Checklist",
    description:
      "Jesus Festival Hamilton starts Friday, September 4 at Gage Park. Get the final times, live weather, packing list, Main and Ottawa detour, offline app and five-minute before-you-go plan.",
    eyebrow: "Tomorrow at Gage Park",
    emoji: "🙌",
    date: "2026-09-03",
    readMins: 5,
    body: [
      { t: "p", text: "**Tomorrow we begin.** Jesus Festival opens at Gage Park on Friday, September 4 at 6:00 PM. Pure Worship Night begins at 6:30 PM and continues until 9:00 PM. Then Saturday’s free Family Festival Day runs from 10:00 AM–7:00 PM, with the full stage program from 11:00 AM–7:00 PM." },
      { t: "p", text: "You do not need a ticket, an account or a perfect plan. But five quiet minutes tonight can remove most of tomorrow’s stress. We built the new [Festival Go Bag](https://www.jesusfestival.app/before-you-go) to walk through all five steps on one screen." },
      { t: "h2", text: "1. Save the app before the park gets busy" },
      { t: "p", text: "A crowded park can mean a crowded mobile network. Open the Festival Go Bag on reliable Wi-Fi and tap **Save now**. The app waits for a real completion response before marking the offline step ready. Your schedule, map, help points and key guides can then keep opening if the signal becomes slow or disappears." },
      { t: "h2", text: "2. Pack for two different festival days" },
      { t: "p", text: "Friday is an evening worship gathering. Saturday is a long open-air family day. The basics are a lawn chair or blanket, a filled refillable water bottle, comfortable shoes, a charged phone or power bank, sun protection for Saturday and a layer for Friday evening." },
      { t: "p", text: "The [What to Bring planner](https://www.jesusfestival.app/what-to-bring) shows the live Gage Park forecast and can adapt the list for children, comfort and accessibility needs, or a volunteer day. The forecast can still move, so check it again shortly before leaving." },
      { t: "h2", text: "3. Do not let Main and Ottawa surprise you" },
      { t: "p", text: "The City of Hamilton says the Main Street East and Ottawa Street North intersection is fully closed during the festival period. HSR Routes **1/1A King, 10 B-Line Express and 41 Mohawk** are detoured around the construction, with some stops moved or closed." },
      { t: "p", text: "Use the [current Gage Park arrival guide](https://www.jesusfestival.app/getting-to-gage-park), check your navigation or HSR information immediately before leaving, and give yourself more time than the normal trip. Gage Park has public parking, but a festival-day space is never guaranteed. HSR, carpooling, rideshare, cycling and walking are all worth considering." },
      { t: "h2", text: "4. Pick the meeting landmark before anyone wanders" },
      { t: "p", text: "A meeting point chosen after someone is already missing is too late. Open the [festival map](https://www.jesusfestival.app/map), drop a private pin near a permanent landmark and tell your group the exact side you mean. Your pin remains on your device unless you deliberately share it." },
      { t: "p", text: "If a child or another person becomes separated from the group, go to the Info and Lost Child Point shown approximately on the map and follow current on-site signs. For first aid, use the mapped First Aid point and ask a volunteer. Call 911 first for any serious or life-threatening emergency." },
      { t: "h2", text: "5. Star the moments you would hate to miss" },
      { t: "p", text: "Friday worship begins at 6:30 PM. Saturday’s stage begins at 11:00 AM, and the updated run of show continues through the 7:00 PM final prayer. Open the [live schedule](https://www.jesusfestival.app/schedule), star your moments and export your personal lineup if a calendar reminder will help." },
      { t: "list", items: [
        "**Friday:** gates at 6:00 PM · Pure Worship Night 6:30–9:00 PM.",
        "**Saturday:** festival activities 10:00 AM–7:00 PM · stage 11:00 AM–7:00 PM.",
        "**Admission:** completely free · no ticket required · all ages welcome.",
        "**Location:** Gage Park, 1000 Main Street East, Hamilton, Ontario.",
        "**Best live screen:** [Day-Of Mode](https://www.jesusfestival.app/day-of) for what is happening now, what comes next, the map, help and offline essentials.",
      ] },
      { t: "h2", text: "There is still time to invite one person" },
      { t: "p", text: "This may be the easiest invitation you make all year: *Jesus Festival starts tomorrow at Gage Park. It is free. Want to come with me?* Send the [Festival Go Bag](https://www.jesusfestival.app/before-you-go) with it so they have every practical detail in one place." },
      { t: "quote", text: "Let us go to the house of the Lord.", ref: "Psalm 122:1" },
      { t: "p", text: "The schedules are ready. The app is ready. The park is waiting. More importantly, people are coming who need hope, prayer, joy and an encounter with Jesus. We cannot wait to worship with you tomorrow." },
    ],
    faqs: [
      { question: "What time does Jesus Festival start tomorrow?", answer: "Jesus Festival opens Friday, September 4, 2026 at 6:00 PM at Gage Park. Pure Worship Night begins at 6:30 PM and concludes at 9:00 PM." },
      { question: "Do I need a ticket for Jesus Festival Hamilton?", answer: "No. Jesus Festival is completely free, no admission ticket is required and all ages are welcome. Food truck, vendor and official shop purchases are optional." },
      { question: "What should I bring to Jesus Festival?", answer: "Bring a lawn chair or blanket, a filled refillable water bottle, comfortable shoes, a charged phone or power bank, sun protection for Saturday and a layer for Friday evening. Check the live Gage Park forecast shortly before leaving." },
      { question: "How do I get to Jesus Festival during the Main and Ottawa closure?", answer: "Check current navigation and HSR information before leaving, use the Jesus Festival arrival guide and allow extra time. HSR Routes 1/1A King, 10 B-Line Express and 41 Mohawk are detoured around the Main and Ottawa closure." },
      { question: "Will the Jesus Festival app work offline?", answer: "Yes. Open the Festival Go Bag on a reliable connection and tap Save now. Once the app confirms completion, the schedule, map, help points and key guides are saved for offline use." },
    ],
    sources: [
      { name: "Jesus Festival — Official Hamilton 2026 Information", url: "https://www.jesusfestival.ca/" },
      { name: "City of Hamilton — Gage Park Features and Services", url: "https://www.hamilton.ca/things-do/venues-facilities-bookings/event-planning-information/event-locations" },
      { name: "City of Hamilton — Current HSR Schedules and Detours", url: "https://www.hamilton.ca/home-neighbourhood/hsr/schedule-route-tools/schedules-detours" },
      { name: "City of Hamilton — Fall 2026 HSR and Main and Ottawa Construction Update", url: "https://www.hamilton.ca/city-council/news-notices/news-releases/bus-news-fall-2026" },
    ],
    related: ["JesusFestival.ca", "LoveonHamilton.com", "ThyKingdom.net"],
  },
  {
    slug: "jesus-festival-saturday-extended-updated-schedule-2026",
    title: "Jesus Festival Saturday Is Now 10 AM–7 PM: Updated Stage Schedule",
    description:
      "Jesus Festival Family Festival Day has been extended by one hour. See the September 5, 2026 stage schedule from 11 AM–7 PM, artist times, speakers and planning notes.",
    eyebrow: "Important schedule update",
    emoji: "⏰",
    date: "2026-09-01",
    readMins: 6,
    body: [
      { t: "p", text: "More time together at Gage Park: **Saturday’s Family Festival Day is now 10:00 AM–7:00 PM**. The festival opens at 10:00 AM, the stage program begins at 11:00 AM, and the final prayer and encouragement begins at 7:00 PM." },
      { t: "p", text: "The artist and speaker times have moved later to fit the extended day. If you previously saved a screenshot, shared a plan or exported your lineup, use the [live Jesus Festival schedule](https://www.jesusfestival.app/schedule) as the current source and export it again." },
      { t: "h2", text: "Saturday at a glance" },
      { t: "list", items: [
        "**10:00 AM:** Family Festival Day opens—come enjoy the park, food trucks, vendors, Kids Zone and activities.",
        "**11:00 AM:** The stage opens with welcome and prayer.",
        "**11:15 AM–7:00 PM:** Artists, worship, speakers, testimonies and united moments fill the stage program.",
        "**7:00 PM:** Daniel & Katie lead the final prayer and encouragement as the festival closes.",
        "**MCs:** JJ & Rachel will guide the day, keep the program moving and fill the natural gaps between stage moments.",
      ] },
      { t: "h2", text: "Updated Saturday stage schedule" },
      { t: "p", text: "These are the best current stage times. Each band’s combined music time is approximately one hour, with speakers and sound checks woven between sets." },
      { t: "list", items: [
        "**11:00 AM — Stage Welcome & Prayer:** opening welcome and prayer with MCs JJ & Rachel.",
        "**11:15 AM — Terry Posthumus:** singer-songwriter and worship leader opening the music program.",
        "**12:30 PM — I Am Second / e3 Canada:** Tanya shares while Open Heaven prepares.",
        "**12:50 PM — Open Heaven, Set 1.**",
        "**1:20 PM — Pastor Joanna Adams:** 20-minute message.",
        "**1:40 PM — Shofars & Pastors on Stage:** a 20-minute moment of church unity.",
        "**2:00 PM — Open Heaven, Set 2:** worship continues.",
        "**2:20 PM — Rachel Shares:** story while ACTS Kingdom Sound Worship prepares.",
        "**2:40 PM — ACTS Kingdom Sound Worship, Set 1.**",
        "**3:10 PM — Rachel Shares:** 20-minute story.",
        "**3:30 PM — ACTS Kingdom Sound Worship, Set 2:** worship continues.",
        "**3:50 PM — Pastor Charles from Bethel:** sharing while Ant Lee Jr. prepares.",
        "**4:10 PM — Ant Lee Jr., Set 1:** Christian hip-hop.",
        "**4:40 PM — Ant Lee Jr. Testimony:** 20-minute testimony.",
        "**5:00 PM — Ant Lee Jr., Set 2:** the music continues.",
        "**5:20 PM — Daughters of Scripture:** sharing while Friday Night Prayer prepares.",
        "**5:40 PM — Friday Night Prayer, Set 1.**",
        "**6:10 PM — Sons of Scripture:** 20-minute message.",
        "**6:30 PM — Friday Night Prayer, Set 2:** worship continues.",
        "**7:00 PM — Final Prayer:** Daniel & Katie close with prayer and encouragement.",
      ] },
      { t: "h2", text: "A live day has breathing room" },
      { t: "p", text: "This is an outdoor festival, not a television broadcast. Stage times may shift a little while artists change over, stories unfold and the team keeps the day moving. JJ & Rachel will MC the program and help fill those natural gaps. The app’s live Schedule screen is the best place to see what is on now and what is next." },
      { t: "h2", text: "Three things to update in your plan" },
      { t: "list", items: [
        "**Your ride home:** Saturday now closes one hour later. Update pickups, HSR planning and your group meeting time.",
        "**Your personal lineup:** artist and speaker times have moved. Open [Find Your Festival Moments](https://www.jesusfestival.app/find-your-moments), review your picks and export a fresh calendar.",
        "**Your packing plan:** the longer day means one more hour outdoors. Bring water, sun protection, a charged phone and the layer or comfort items your visit needs. Use the [personalized What to Bring planner](https://www.jesusfestival.app/what-to-bring).",
      ] },
      { t: "quote", text: "Let all things be done decently and in order.", ref: "1 Corinthians 14:40 (NKJV)" },
      { t: "p", text: "Jesus Festival remains completely free, all ages and open to everyone. Friday’s Pure Worship Night is unchanged at 6:00–9:00 PM. Saturday is the day that grew: **10:00 AM–7:00 PM, with the stage from 11:00 AM–7:00 PM.** We cannot wait to worship Jesus with Hamilton." },
    ],
    faqs: [
      { question: "What are the new Jesus Festival Saturday hours?", answer: "Family Festival Day on Saturday, September 5, 2026 now runs from 10:00 AM–7:00 PM at Gage Park. The festival opens at 10:00 AM and the stage program runs from 11:00 AM–7:00 PM." },
      { question: "What time does the Jesus Festival stage begin on Saturday?", answer: "The Saturday stage begins with welcome and prayer at 11:00 AM. Terry Posthumus is scheduled at 11:15 AM, and the stage continues through the 7:00 PM final prayer and encouragement." },
      { question: "Who are the MCs for Jesus Festival Saturday?", answer: "JJ & Rachel are the Saturday MCs. They will keep the stage program moving and help fill gaps between artists, speakers and sound checks." },
      { question: "When does Ant Lee Jr. perform at Jesus Festival 2026?", answer: "Ant Lee Jr. is scheduled for music at 4:10 PM and 5:00 PM on Saturday, with his testimony at 4:40 PM between the two sets." },
      { question: "Can the Saturday schedule change during the festival?", answer: "Yes. The published schedule is the best current plan, but stage times may shift slightly during the live outdoor event. Check the Jesus Festival app Schedule and News screens for the latest information." },
    ],
    sources: [
      { name: "Jesus Festival — Official Hamilton 2026 Information", url: "https://www.jesusfestival.ca/" },
      { name: "Jesus Festival App — Live 2026 Schedule", url: "https://www.jesusfestival.app/schedule" },
    ],
    related: ["JesusFestival.ca", "ThyKingdom.net"],
  },
  {
    slug: "free-things-to-do-hamilton-september-2026",
    title: "Free Things to Do in Hamilton in September 2026",
    description:
      "A practical, date-checked guide to free Hamilton events in September 2026—including Jesus Festival, Supercrawl, Open Streets and a great day at Gage Park.",
    eyebrow: "Hamilton weekend guide",
    emoji: "🌆",
    date: "2026-08-17",
    readMins: 8,
    body: [
      { t: "p", text: "September is one of the best months to explore Hamilton without spending much. The heat eases, the city calendar fills up, and some of the year’s biggest gatherings are completely free." },
      { t: "p", text: "This guide is **current as of August 17, 2026** and uses official City of Hamilton, Tourism Hamilton and event sources. Dates, transit and weather plans can still change, so follow the linked official pages before you travel." },
      { t: "h2", text: "At a glance: free Hamilton events in September 2026" },
      { t: "list", items: [
        "**September 4:** Ability First Accessibility Fair at Hamilton City Hall, 11:00 AM–3:00 PM, with the Accessibility Awards presented at 2:00 PM.",
        "**September 4–5:** Jesus Festival Hamilton at Gage Park—Friday worship night and a full Saturday family festival.",
        "**September 11–13:** Supercrawl on James Street North, with free music, art, performances, vendors and family-friendly programming.",
        "**September 27:** Open Streets on King Street East, a free, family-friendly day built around walking, rolling, cycling and community activity.",
        "**Any day:** Explore Gage Park’s 71 acres of lawns, trails, gardens, playgrounds and public spaces.",
      ] },
      { t: "h2", text: "September 4: Ability First Accessibility Fair" },
      { t: "p", text: "Hamilton’s Ability First Accessibility Fair is scheduled for **Friday, September 4 from 11:00 AM to 3:00 PM** on the east walkway at Hamilton City Hall. The City says the event brings together organizations and services that help make Hamilton more accessible, and the 2026 Accessibility Awards are scheduled for 2:00 PM." },
      { t: "p", text: "This is a useful first stop for families, caregivers, community leaders and anyone who wants to learn more about accessibility in Hamilton. Check the [City of Hamilton announcement](https://www.hamilton.ca/city-council/news-notices/news-releases/nominations-open-hamiltons-3rd-annual-accessibility-awards) for the latest event details." },
      { t: "h2", text: "September 4–5: Jesus Festival Hamilton at Gage Park" },
      { t: "p", text: "Jesus Festival is a **free, no-ticket-required outdoor festival** at Gage Park, 1000 Main Street East. Friday’s Pure Worship Night runs from 6:00–9:00 PM. Saturday’s extended all-ages festival runs from 10:00 AM–7:00 PM, with the stage from 11:00 AM–7:00 PM plus live worship and music, testimonies, prayer, baptisms, a Kids Zone, bouncy castles, lawn games and food trucks." },
      { t: "p", text: "You can stay for one set or make a weekend of it. Start with the [complete Hamilton festival guide](https://www.jesusfestival.app/jesus-festival-hamilton), then use [Build My Festival Plan](https://www.jesusfestival.app/jesus-festival-hamilton#build-my-plan) to create an arrival, travel and packing plan that stays privately on your device." },
      { t: "p", text: "If mobility, sensory comfort, hearing or vision access, medication, a service animal or a support person affects your day, use the [Jesus Festival Accessibility and Comfort Guide](https://www.jesusfestival.app/accessibility). It separates confirmed Gage Park and HSR facts from event-day services that still need to be checked, and builds a private Comfort Plan without an account." },
      { t: "p", text: "Bringing children? The [parent’s festival survival guide](https://www.jesusfestival.app/blog/bringing-the-kids-to-jesus-festival) covers meeting points, what to pack and how to plan around naps. Save the [offline essentials](https://www.jesusfestival.app/offline) before leaving home so your core festival information remains available if the park network is crowded." },
      { t: "h2", text: "Make a free Gage Park day" },
      { t: "p", text: "Even without an event, Gage Park is worth exploring. The City lists **28.8 hectares—about 71 acres—of parkland**, along with the George R. Robinson Bandshell, trails, playgrounds, gardens, picnic areas, washrooms and potable water near washroom buildings." },
      { t: "list", items: [
        "Walk the loop and explore the gardens before the busiest part of the day.",
        "Bring lunch and use one of the park’s picnic areas instead of buying every meal out.",
        "Pack refillable bottles; the City lists potable water near the washroom buildings.",
        "Give children a clear meeting point before they run toward the playground or event activities.",
        "Check the City park page for current construction, parking and facility notices.",
      ] },
      { t: "p", text: "The park is large and event-day layouts can change. The City’s [Gage Park event-location page](https://www.hamilton.ca/things-do/venues-facilities-bookings/event-planning-information/event-locations) is the best source for permanent park facilities, while the festival app provides the event-specific map." },
      { t: "h2", text: "September 7: plan around the Labour Day HSR schedule" },
      { t: "p", text: "If you are planning a free park or waterfront day on **Labour Day, Monday, September 7**, Hamilton’s official 2026 holiday schedule says HSR will operate on a **Sunday service schedule**. The City also notes that routes 12 and 42 do not operate on the Sunday schedule." },
      { t: "p", text: "Use the [official HSR holiday schedule](https://www.hamilton.ca/home-neighbourhood/hsr/schedule-route-tools/hsr-holiday-schedules) and current trip planner shortly before leaving. A holiday timetable can turn a ten-minute connection into a much longer wait if you plan from a normal weekday screenshot." },
      { t: "h2", text: "September 11–13: Supercrawl" },
      { t: "p", text: "Supercrawl returns to James Street North from **Friday, September 11 through Sunday, September 13, 2026**. Tourism Hamilton lists it as a free, family-friendly festival bringing together music, art, fashion, performances, vendors and food." },
      { t: "p", text: "Because it stretches across multiple days and a busy downtown corridor, pick a smaller goal instead of trying to see everything. Choose one performance window, allow time to walk, and confirm the latest lineup and road information on the [official Tourism Hamilton listing](https://tourismhamilton.com/event/supercrawl/)." },
      { t: "h2", text: "September 27: Open Streets Hamilton" },
      { t: "p", text: "Open Streets is scheduled for **Sunday, September 27, 2026**, beginning at 10:00 AM on King Street East. Tourism Hamilton describes it as a free, family-friendly event where people can walk, cycle, roll and enjoy community programming without normal through traffic." },
      { t: "p", text: "Bring a bike, stroller, mobility device or comfortable shoes and treat the street itself as the destination. Check the [official Open Streets listing](https://tourismhamilton.com/event/open-streets-2/) closer to the date for the current route and hours." },
      { t: "h2", text: "How to have a better free day out" },
      { t: "list", items: [
        "**Verify the event on the morning you go.** Outdoor plans, route closures and hours can change.",
        "**Pack water, snacks and a layer.** A free outing becomes expensive quickly when everyone arrives hungry and unprepared.",
        "**Choose one anchor activity.** Build the day around the one set, neighbourhood or family activity you care about most.",
        "**Use current transit information.** Holiday schedules and event detours are more reliable than saved screenshots.",
        "**Download essential details.** Save addresses, meeting points and your return route before entering a busy event area.",
        "**Leave margin.** The best free festivals are popular. Twenty extra minutes protects the mood of the whole day.",
      ] },
      { t: "p", text: "Hamilton’s September calendar proves that a memorable weekend does not need an expensive ticket. Pick one event, invite one person, pack what you need and enjoy the city you already live in." },
    ],
    faqs: [
      { question: "What free events are happening in Hamilton in September 2026?", answer: "Major free September events include the Ability First Accessibility Fair on September 4, Jesus Festival Hamilton on September 4–5, Supercrawl on September 11–13 and Open Streets on September 27. Always confirm the latest details with the official organizer before travelling." },
      { question: "Is Jesus Festival Hamilton free?", answer: "Yes. Jesus Festival Hamilton is completely free and no ticket is required. It takes place September 4–5, 2026 at Gage Park. Food truck purchases and official merchandise are optional." },
      { question: "What free family events are in Hamilton in September?", answer: "Jesus Festival on September 5, Supercrawl from September 11–13 and Open Streets on September 27 are all listed as free and family-friendly. Gage Park is also a useful free outdoor destination for playgrounds, trails, gardens and picnics." },
      { question: "Does HSR run on Labour Day 2026?", answer: "Yes. On Labour Day, Monday, September 7, 2026, HSR is scheduled to run Sunday service. The City says routes 12 and 42 do not operate on the Sunday schedule, so check the current official trip planner before leaving." },
      { question: "Where is Gage Park in Hamilton?", answer: "Gage Park is at 1000 Main Street East in Hamilton, Ontario, between Main Street East, Gage Avenue South, Lawrence Road and Rothsay Avenue." },
    ],
    sources: [
      { name: "City of Hamilton — 2026 Accessibility Awards and Ability First Accessibility Fair", url: "https://www.hamilton.ca/city-council/news-notices/news-releases/nominations-open-hamiltons-3rd-annual-accessibility-awards" },
      { name: "City of Hamilton — Gage Park Event Location", url: "https://www.hamilton.ca/things-do/venues-facilities-bookings/event-planning-information/event-locations" },
      { name: "City of Hamilton — HSR Holiday Schedules", url: "https://www.hamilton.ca/home-neighbourhood/hsr/schedule-route-tools/hsr-holiday-schedules" },
      { name: "Tourism Hamilton — Supercrawl", url: "https://tourismhamilton.com/event/supercrawl/" },
      { name: "Tourism Hamilton — Open Streets", url: "https://tourismhamilton.com/event/open-streets-2/" },
      { name: "Jesus Festival — Official Event Website", url: "https://www.jesusfestival.ca/" },
    ],
    related: ["JesusFestival.ca", "LoveonHamilton.com", "ThyKingdom.net"],
  },
  {
    slug: "bringing-the-kids-to-jesus-festival",
    title: "Bringing the Kids: A Parent's Survival Guide",
    description:
      "A free outdoor festival with thousands of people and a toddler who has opinions. What to pack, where to sit, what to do when someone wanders off — and why it's worth the effort.",
    eyebrow: "For parents",
    emoji: "🎈",
    date: "2026-08-14",
    readMins: 6,
    body: [
      { t: "p", text: "Taking small children to a large outdoor event is a calculation every parent runs. Free, ten minutes away, food trucks, bouncy castles — versus heat, crowds, naps, and the particular horror of losing sight of a four-year-old in a field of strangers." },
      { t: "p", text: "Saturday's Family Festival Day is genuinely built for this. But a good day and a hard day are separated by about six decisions you make before you leave the house. Here they are." },
      { t: "h2", text: "Sit at the back. Seriously." },
      { t: "p", text: "Every instinct says get close to the stage. With kids, do the opposite. The back and the edges of the lawn are where you can stand up, walk a grizzly baby in a circle, let a toddler roll around, and leave for the washroom without climbing over forty people." },
      { t: "p", text: "You'll hear everything. Nobody near you will mind noise. And you're ten steps from the exit when it's time." },
      { t: "h2", text: "Do the lost-child conversation before you arrive" },
      { t: "p", text: "This is the one thing worth being slightly systematic about, and it takes two minutes in the car:" },
      { t: "list", items: [
        "**Show them the Info & Lost Child Point on the map** in the app before you get there, and again when you arrive. It's the meeting point the whole team works from and the first place anyone will bring a child who's on their own.",
        "**Write your phone number on their arm** in biro, under the sleeve. Low tech, no battery, works when they're too upset to recite it.",
        "**Photograph them when you arrive**, in what they're actually wearing. If you ever need to describe them, you'll be holding the answer.",
        "**Teach them who to look for** — someone with a festival lanyard, or a mum with her own kids. \"Find a helper\" beats \"stay put\" for a child who is already moving.",
        "**Pick a landmark** as your family meeting point. The Gage Family Fountain is the easiest one in the park to describe and to find.",
      ] },
      { t: "p", text: "You will almost certainly not need any of this. It costs two minutes and it buys you the ability to relax, which is the actual goal." },
      { t: "h2", text: "The bag" },
      { t: "list", items: [
        "**A blanket bigger than you think.** It's your base, your table and your nap zone.",
        "**Sunscreen, and then sunscreen again at 2pm.** Early September sun in an open park is deceptive — there's a breeze, so nobody feels like they're burning until they are.",
        "**Water bottles.** There are drinking fountains in the park, so bring empties and fill up.",
        "**A change of clothes.** The spray pad is right there and children have no self-control about water. Assume they get soaked; be delighted rather than annoyed.",
        "**Snacks they already like.** Food trucks are great and also a queue with a hungry child in it.",
        "**Ear defenders for babies and toddlers.** Live sound at an outdoor stage is loud. Small ears aren't finished developing and this is genuinely worth doing.",
        "**A power bank.** You'll take 200 photos and the park signal will drain your battery hunting for a tower.",
      ] },
      { t: "h2", text: "Plan around the nap, not against it" },
      { t: "p", text: "Saturday now runs 10:00 AM to 7:00 PM, with the stage from 11:00 AM. Nobody needs to do all nine hours with a toddler. Pick your window—the Kids Zone and activities in the morning, or the afternoon sets and final prayer—and leave while everyone is still enjoying themselves." },
      { t: "p", text: "Leaving one hour early with a happy child is a completely different memory from leaving one hour late with a melting one. The [full schedule](https://www.jesusfestival.app/schedule) is in the app, so you can pick your window before you leave home." },
      { t: "h2", text: "Lower the bar for what counts as a good day" },
      { t: "p", text: "You may not hear a full talk. You may spend forty minutes at a bouncy castle and miss the set you came for. A friend will find you at the exact moment someone needs the toilet." },
      { t: "p", text: "That is not a failed day. Your kids will remember that church was outdoors and there was a slide and everyone was happy. That's the memory. The theology can come later — and it will come more easily to a child who associates all this with joy rather than with sitting still." },
      { t: "h2", text: "Why bother at all" },
      { t: "p", text: "When people started bringing children to Jesus, his own disciples — the serious, ministry-minded ones — tried to shoo them away. They had the reasonable adult view that this was an important gathering and children were a disruption." },
      { t: "quote", text: "Let the little children come to me, and do not hinder them, for the kingdom of God belongs to such as these.", ref: "Mark 10:14" },
      { t: "p", text: "The word Mark uses for Jesus' reaction is strong — he was indignant. Not mildly amused at the fuss. Annoyed, on behalf of the children, at the adults managing access to him." },
      { t: "p", text: "So bring them. Bring them noisy and sticky and mid-tantrum. They are not an interruption to what's happening at Gage Park; they're a fairly large part of the point." },
      { t: "p", text: "There's a [park map](https://www.jesusfestival.app/map) with the Kids Zone, the spray pad, the washrooms, first aid and the lost-child point all marked, and it works offline once you've installed the app — worth doing before you leave, because the signal in the park will not be there when you want it." },
      { t: "p", text: "See you on the grass. Sit at the back. 💛" },
    ],
    related: ["JesusFestival.ca", "LoveonHamilton.com", "IAmReborn.net"],
  },
  {
    slug: "never-been-to-anything-like-this",
    title: "If You've Never Been to Anything Like This Before",
    description:
      "Someone invited you to Jesus Festival and you said yes before you thought it through. Here's honestly what happens, what nobody will ask of you, and why you're more welcome than you think.",
    eyebrow: "For the first-timer",
    emoji: "🫂",
    date: "2026-08-13",
    readMins: 6,
    body: [
      { t: "p", text: "Someone you trust invited you to a Christian festival at Gage Park. You said yes — maybe because you love them, maybe because it's free, maybe because some quiet part of you was curious. And now it's a few weeks out and you're wondering what exactly you agreed to." },
      { t: "p", text: "This is written for you specifically. Not for the person who invited you. You." },
      { t: "h2", text: "What is actually going to happen" },
      { t: "p", text: "It's an outdoor festival in a public park. There's a stage with bands on it. There are food trucks. There are bouncy castles and lawn games and a spray pad, and a lot of kids running around with their faces painted. People bring lawn chairs and blankets and sit on the grass. Some of them will be worshipping with their hands in the air. Some will be eating tacos. Both of those are normal here." },
      { t: "p", text: "Between the music, people get up and talk — usually for ten or fifteen minutes. Some of them will explain what Christians believe about Jesus. Some will tell you what happened in their own life. On Saturday there are baptisms, which mostly looks like people getting joyfully soaked while a crowd cheers." },
      { t: "p", text: "You can look at the whole [run of show](https://www.jesusfestival.app/schedule) if it helps to know. Some people find the unknown much worse than the plan." },
      { t: "h2", text: "What nobody is going to ask you to do" },
      { t: "list", items: [
        "**Nobody will ask you for money.** It's free. There's no ticket, no gate, no collection, no envelope. If someone tells you what it cost to put on, it's because they're grateful, not because they're hinting.",
        "**Nobody will single you out.** No spotlight, no stand-up-if-you're-new, no raise-your-hand-if-you're-visiting. You can arrive, sit down, and leave without speaking to anyone.",
        "**Nobody needs you to perform.** You don't have to sing. You don't have to close your eyes or lift your hands or say amen. Sitting quietly through a worship set is a completely normal thing to do and nobody is watching you.",
        "**Nobody is going to corner you.** If someone offers to pray for you and you'd rather they didn't, \"no thanks\" is a full sentence and it will be respected the first time.",
        "**You can leave whenever you want.** It's a public park. There's no exit interview.",
      ] },
      { t: "h2", text: "The awkward part, named out loud" },
      { t: "p", text: "Here's the thing that's probably actually bothering you: you don't want to be the person who doesn't know the words. You don't want to be handled. You don't want somebody's project." },
      { t: "p", text: "That's fair. Churches have earned some of that suspicion, and pretending otherwise would be insulting. So let me just say plainly: you are not a project. Your friend didn't invite you to close a deal. They invited you because something happened to them that they can't stop being glad about, and you're one of the people they'd most want to be there." },
      { t: "p", text: "That's it. That's the whole motive." },
      { t: "h2", text: "What Jesus was actually like with outsiders" },
      { t: "p", text: "If your picture of Christianity is mostly rules and disapproval, it's worth knowing that the religious people of Jesus' own day complained about the exact opposite. Their objection was that he was too welcoming — that he kept eating dinner with the wrong people." },
      { t: "quote", text: "Now the tax collectors and sinners were all gathering around to hear Jesus. But the Pharisees and the teachers of the law muttered, \"This man welcomes sinners and eats with them.\"", ref: "Luke 15:1–2" },
      { t: "p", text: "That was the accusation. He welcomes the wrong people and shares meals with them. He never denied it — he told three stories in a row about how much God enjoys finding someone who was lost." },
      { t: "p", text: "So if you turn up at Gage Park half-sceptical, with questions you think are too rude to ask, eating a taco through the sermon — you are, historically speaking, exactly the demographic he went out of his way for." },
      { t: "h2", text: "Practical things that will make the day better" },
      { t: "list", items: [
        "**Bring a chair or a blanket.** The lawn fills from the front. This is the single most common regret.",
        "**Come with your person.** Arrive together, sit together. Having one familiar face changes everything about a new room — or a new field.",
        "**Saturday is the easy way in.** 10am to 7pm, families everywhere, food, games and a stage program from 11am. It's much less intense than Friday's worship night if intensity is what you're worried about.",
        "**Eat something.** Genuinely. Most \"I feel weird here\" is 30% social and 70% low blood sugar in the sun.",
        "**Set your expectations at zero.** You don't owe the day a decision, a feeling, or a conclusion. You're allowed to just be there.",
      ] },
      { t: "p", text: "The [park map](https://www.jesusfestival.app/map) shows where the food, the washrooms, the shade and the exits are, and the [FAQ](https://www.jesusfestival.app/faq) answers the practical stuff. There's also a prayer tent, and the only thing you need to know about it is that you never have to go near it." },
      { t: "h2", text: "And if something does happen" },
      { t: "p", text: "Sometimes people come to a thing like this fully intending to stay on the edge, and something lands anyway. A line in a song. A stranger's story that sounds too much like their own. A sense — hard to describe later — of being known." },
      { t: "p", text: "If that happens to you, you don't have to announce it or do anything about it in the moment. You can drive home and think about it for a month. But there's a page in this app that just quietly explains what it would mean and what you might do next, with no sign-up and no email and nobody following up: [I said yes to Jesus](https://www.jesusfestival.app/i-said-yes)." },
      { t: "p", text: "And if nothing happens? You had a free day in a park with someone who loves you, and you ate well. That's not a wasted Saturday." },
      { t: "quote", text: "Taste and see that the Lord is good.", ref: "Psalm 34:8" },
      { t: "p", text: "That's an invitation to try, not a demand to conclude. Come and see for yourself. September 4–5, Gage Park, Hamilton. Bring a chair." },
    ],
    related: ["JesusFestival.ca", "IAmReborn.net", "LoveonHamilton.com"],
  },
  {
    slug: "how-to-pray-for-your-city",
    title: "How to Pray for a City (When It Feels Too Big)",
    description:
      "Praying for a whole city sounds enormous and vague. Scripture makes it surprisingly concrete — five biblical patterns for praying over the streets you actually live on.",
    eyebrow: "Prayer",
    emoji: "🏙️",
    date: "2026-08-11",
    readMins: 7,
    body: [
      { t: "p", text: "\"Pray for our city\" is one of those phrases everyone nods along to and almost nobody knows how to actually do. You bow your head, you think *God, bless Hamilton*, and then there's a long pause where you realise you have no idea what comes next." },
      { t: "p", text: "The problem isn't your faith. It's scale. A city is 570,000 people and you have one mouth and about four minutes. So the mind reaches for something enormous and generic, and generic prayer is hard to keep doing." },
      { t: "p", text: "Scripture is far more concrete than we are. Here are five patterns straight out of the text — and none of them require you to pray for half a million people at once." },
      { t: "h2", text: "1. Pray for its peace, not its conversion statistics" },
      { t: "p", text: "God's instruction to exiles living in a city they didn't choose and didn't like is startlingly practical:" },
      { t: "quote", text: "Seek the peace and prosperity of the city to which I have carried you. Pray to the Lord for it, because if it prospers, you too will prosper.", ref: "Jeremiah 29:7" },
      { t: "p", text: "That's Babylon. Not Jerusalem. God tells his people to pray for the flourishing of a pagan city — its economy, its safety, its wellbeing — and ties their own future to it. The Hebrew word there is *shalom*: not merely the absence of conflict but wholeness, things working as they should." },
      { t: "p", text: "So pray for the hospital. The school board. The housing crisis. The bus routes. The people making decisions at City Hall this week. That's not a warm-up to real prayer; Jeremiah says that *is* the assignment." },
      { t: "h2", text: "2. Walk it, and let what you see set the agenda" },
      { t: "p", text: "When Nehemiah wanted to pray for Jerusalem, he didn't start with a strategy. He went out at night and looked at the walls." },
      { t: "quote", text: "By night I went out through the Valley Gate… examining the walls of Jerusalem, which had been broken down.", ref: "Nehemiah 2:13" },
      { t: "p", text: "He inspected the damage before he asked for anything. Then he wept, then he prayed, then he built." },
      { t: "p", text: "Try the same order. Walk one street of your own neighbourhood slowly with your phone in your pocket. Notice the boarded-up unit, the overflowing bin, the man asleep in the doorway, the young family who just moved in. Pray for what your eyes actually land on. A prayer walk beats a prayer list because the city writes the list for you." },
      { t: "h2", text: "3. Name individuals, not categories" },
      { t: "p", text: "Jesus prayed for cities and he wept over them — but when he taught prayer, he pushed relentlessly towards the specific: this neighbour, this debt, this daily bread. Paul does the same, filling his letters with names." },
      { t: "p", text: "\"Bless the lonely people of Hamilton\" is hard to pray twice. \"Be with Ray on the corner, who lost his wife in March\" is a prayer you'll still be praying next year." },
      { t: "p", text: "If you don't know who to name, that's the real thing to fix first — and it's a mapping problem more than a prayer problem. [Oikos Map](https://www.oikosmap.com) is a free tool for writing down the eight or ten people God has already placed around you, so that praying for your city becomes praying for people whose names you know." },
      { t: "h2", text: "4. Pray with other people, out loud" },
      { t: "p", text: "Almost every city-shaped prayer in the Bible is corporate. The early church prayed together and the room shook. Something happens when prayer stops being private that doesn't happen when it stays private." },
      { t: "quote", text: "For where two or three gather in my name, there am I with them.", ref: "Matthew 18:20" },
      { t: "p", text: "This is the simplest and most-avoided step, because praying aloud in front of another human being is mildly terrifying. Do it badly. Nobody is grading it. Pray with your spouse, or one friend on a phone call, or on the [Prayer Wall](https://www.jesusfestival.app/prayer), where you can post one line and find other people already holding up the same thing." },
      { t: "h2", text: "5. Pray with your hands as well as your mouth" },
      { t: "p", text: "James is blunt about the version of prayer that stays entirely verbal — the *be warmed and filled* prayer offered to someone who needs a coat. He calls that faith dead." },
      { t: "quote", text: "Suppose a brother or a sister is without clothes and daily food. If one of you says to them, \"Go in peace; keep warm and well fed,\" but does nothing about their physical needs, what good is it?", ref: "James 2:15–16" },
      { t: "p", text: "The test of whether you're really praying for your city is whether your prayers keep costing you things — a Saturday, a meal, a difficult conversation, a cheque. When you ask God to move in a neighbourhood, be ready for the answer to be *you, on Tuesday*." },
      { t: "p", text: "That's most of what [Love on Hamilton](https://www.loveonhamilton.com) is: prayer that got up off the sofa. And it's why Jesus Festival exists at all — a weekend of the whole church praying for one city with its hands." },
      { t: "h2", text: "The promise underneath all of it" },
      { t: "p", text: "There's a reason to keep going when nothing visibly changes for a long time. The promise is not that God will notice a big enough crowd. It's that he is already listening for the smallest voice." },
      { t: "quote", text: "If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven, and I will forgive their sin and will heal their land.", ref: "2 Chronicles 7:14" },
      { t: "p", text: "Notice the order. Humble, pray, seek, turn — then heal. Three of those four happen inside you before anything happens outside you. Revival in a city has almost always started as repentance in a few unremarkable people." },
      { t: "p", text: "So don't try to pray for 570,000 people tonight. Pray for one street, one name, one decision at City Hall, out loud, with somebody. Then do it again tomorrow. Cities have been turned by less." },
      { t: "p", text: "If you want to do it with a few thousand others: September 4–5, Gage Park. That's the plan. [Come and pray with us](https://www.jesusfestival.app/schedule)." },
    ],
    related: ["LoveonHamilton.com", "OikosMap.com", "SeekFirst.World", "ThyKingdom.net"],
  },
  {
    slug: "gage-park-festival-guide",
    title: "The Complete Gage Park Festival Guide for Jesus Festival 2026",
    description:
      "Plan your Jesus Festival Hamilton weekend at Gage Park: where to enter, when to arrive, parking and HSR options, what to pack, family tips and the full September 4–5 schedule.",
    eyebrow: "Plan your weekend",
    emoji: "🗺️",
    date: "2026-08-17",
    readMins: 8,
    body: [
      { t: "p", text: "Jesus Festival Hamilton returns to Gage Park on **Friday, September 4 and Saturday, September 5, 2026**. Admission is completely free, no ticket is required, and everyone is welcome. Friday is an open-air Pure Worship Night from 6:00–9:00 PM; Saturday is an extended all-ages festival day from 10:00 AM–7:00 PM, with the stage from 11:00 AM–7:00 PM." },
      { t: "p", text: "This guide puts the practical details in one place so you can spend less time wondering where to go and more time enjoying the weekend. Save the [official 2026 festival guide](https://www.jesusfestival.app/jesus-festival-hamilton), open the [live schedule](https://www.jesusfestival.app/schedule), and use the new [offline essentials screen](https://www.jesusfestival.app/offline) before you leave home." },
      { t: "h2", text: "Where exactly is Jesus Festival Hamilton?" },
      { t: "p", text: "Jesus Festival is held at **Gage Park, 1000 Main Street East, Hamilton, Ontario**. The park sits between Main Street East, Gage Avenue South, Lawrence Road and Rothsay Avenue. The City of Hamilton describes it as a 71-acre festival park with broad open lawns, walking paths and the George R. Robinson Bandshell." },
      { t: "p", text: "The bandshell is the natural landmark to look for once you are inside the park. Final festival-zone placement—including food trucks, Kids Zone, prayer and baptism areas—can change as the event plan is completed, so check the [in-app map and arrival guide](https://www.jesusfestival.app/map) near festival weekend." },
      { t: "h2", text: "When should I arrive?" },
      { t: "list", items: [
        "**Friday:** gates open at 6:00 PM and worship begins at 6:30 PM. Arriving around opening gives you time to park, choose a lawn spot and settle in before worship.",
        "**Saturday:** the festival begins at 10:00 AM and now runs until 7:00 PM; the stage starts at 11:00 AM. Come early if convenient parking and a favourite lawn location matter to you.",
        "**Families:** build in extra time for unloading chairs, water and children’s supplies. The park is large, so a calm arrival is worth the earlier start.",
      ] },
      { t: "p", text: "There is no box office or ticket line. You can simply arrive and join the festival. Star the sets you do not want to miss in the [personal schedule planner](https://www.jesusfestival.app/schedule), then download both days to your device calendar." },
      { t: "h2", text: "Parking, transit and getting to Gage Park" },
      { t: "p", text: "Parking around Gage Park is limited and spaces can fill quickly. City park information lists 150 park spaces, while the official festival site recommends arriving early or considering transit, rideshare, biking, walking or carpooling. Follow festival signs and volunteer directions when you arrive because event-day traffic flow can differ from an ordinary park visit." },
      { t: "p", text: "Nearby street parking, carpooling, rideshare, cycling, walking and HSR are useful alternatives. Transit schedules and detours can change, so use the [City of Hamilton’s official HSR trip-planning tools](https://www.hamilton.ca/home-neighbourhood/hsr/schedule-route-tools/trip-planning-tools) on the day you travel rather than relying on an old route screenshot." },
      { t: "list", items: [
        "**Driving from downtown or Highway 403:** approach Main Street East toward Gage Avenue, then follow current traffic and event signage.",
        "**Driving from Niagara or the east:** the Red Hill Valley Parkway and Lawrence Road can provide a practical approach, depending on current conditions.",
        "**Using HSR:** plan for Gage Park or 1000 Main Street East and check live detour information before leaving.",
        "**Rideshare:** choose a safe legal drop-off point outside the busiest entrance and expect a short walk.",
      ] },
      { t: "h2", text: "What should I bring to an outdoor festival at Gage Park?" },
      { t: "p", text: "Think comfort, weather and a full day outdoors. The app now includes a private **Festival Ready** checklist that stays on your device and works offline. The essentials are simple:" },
      { t: "list", items: [
        "A lawn chair or picnic blanket",
        "A refillable water bottle",
        "Sunscreen and a hat for Saturday",
        "A light layer for Friday evening",
        "Comfortable walking shoes",
        "Any medications or family supplies you normally carry",
        "A friend, neighbour or family member to experience it with",
      ] },
      { t: "p", text: "The City lists potable water near park washroom buildings and three washroom areas across Gage Park, but event layouts and access points may change. Bring your water bottle filled, use posted facilities and ask a festival volunteer if you need help finding something." },
      { t: "p", text: "Visitors planning around mobility, sensory, hearing, vision or medical needs can use the [Accessibility and Comfort Guide](https://www.jesusfestival.app/accessibility) for confirmed park and HSR information, a private checklist and the questions worth asking before travelling." },
      { t: "h2", text: "Is Jesus Festival good for families?" },
      { t: "p", text: "Yes. Saturday is designed as a free, all-ages family festival with a Kids Zone, bouncy castles, lawn games, food trucks, worship, live music and open green space. Gage Park itself includes playgrounds, gardens and walking paths, although normal park amenities may operate differently during a major event." },
      { t: "p", text: "Take a photo of your group before spreading out, choose an easy-to-recognize meeting point, and make sure children know which festival volunteers to approach if they need help. A small card with a caregiver’s phone number is a useful extra for younger children." },
      { t: "h2", text: "What happens on Friday and Saturday?" },
      { t: "p", text: "Friday’s **Pure Worship Night** opens at 6:00 PM, with worship led by Bethel Gospel Tabernacle from 6:30–9:00 PM. Saturday’s extended **Family Festival Day** runs 10:00 AM–7:00 PM, with the stage from 11:00 AM–7:00 PM featuring Terry Posthumus, Ant Lee Jr., Open Heaven, ACTS Kingdom Sound Worship, Friday Night Prayer, testimonies, prayer, the Gospel, food trucks, family activities and baptisms." },
      { t: "p", text: "Set times can be easier to follow inside the app, especially once you create a personal lineup. The schedule and offline guide are cached for congested park networks, while live news, community features and Shopify inventory reconnect whenever service is available." },
      { t: "h2", text: "Your simplest festival plan" },
      { t: "list", items: [
        "Save September 4–5 using the app’s two-event calendar download.",
        "Open the Festival Ready checklist and pack the night before.",
        "Choose driving, HSR, rideshare, cycling or walking before you leave.",
        "Arrive early enough to park and settle in without rushing.",
        "Star your must-see sets and invite one person to come with you.",
      ] },
      { t: "p", text: "That is all you need. There is no ticket to buy and no special background required. Come as you are, find a place on the grass, and join a whole city lifting up the name of Jesus." },
    ],
    faqs: [
      { question: "When is Jesus Festival Hamilton 2026?", answer: "Jesus Festival Hamilton is September 4–5, 2026. Friday runs from 6:00–9:00 PM, with worship beginning at 6:30 PM. Saturday has been extended to 10:00 AM–7:00 PM, with the stage from 11:00 AM–7:00 PM." },
      { question: "Where is Jesus Festival held?", answer: "Jesus Festival is held at Gage Park, 1000 Main Street East, Hamilton, Ontario. The main City parking entrance is off Lawrence Road, just east of Gage Avenue South." },
      { question: "Is admission free and do I need a ticket?", answer: "Admission is completely free and no ticket is required. Food truck purchases and official merchandise are optional." },
      { question: "Where can I park for Jesus Festival?", answer: "Free festival parking is available but fills quickly. Follow current event signs and volunteer directions. Nearby street parking, HSR, rideshare, cycling and walking are useful alternatives." },
      { question: "What should I bring to Gage Park?", answer: "Bring a lawn chair or blanket, refillable water bottle, sunscreen, hat, comfortable shoes and a layer for Friday evening. The app includes a private offline packing checklist." },
      { question: "Is Jesus Festival family-friendly?", answer: "Yes. Saturday is an all-ages family festival with a Kids Zone, bouncy castles, games, food trucks, live music and open green space." },
    ],
    sources: [
      { name: "City of Hamilton — Gage Park Features and Event Services", url: "https://www.hamilton.ca/things-do/venues-facilities-bookings/event-planning-information/event-locations" },
      { name: "City of Hamilton — Gage Park and Tropical Greenhouse", url: "https://www.hamilton.ca/things-do/parks-green-space/gage-park-tropical-greenhouse" },
      { name: "City of Hamilton — HSR Trip Planning Tools", url: "https://www.hamilton.ca/home-neighbourhood/hsr/schedule-route-tools/trip-planning-tools" },
    ],
    related: ["JesusFestival.ca", "JesusFestivalMovement.com", "LoveonHamilton.com"],
  },
  {
    slug: "the-light-hunt-gage-park-scavenger-hunt",
    title: "The Light Hunt: a Free Scavenger Hunt Hidden Inside Jesus Festival",
    description:
      "Twelve QR codes are hidden around Gage Park at Jesus Festival Hamilton — each one carries Scripture, lights a lamp on your phone, and unlocks shareable badges. Here's how to play.",
    eyebrow: "Play the festival",
    emoji: "🔦",
    date: "2026-08-29",
    readMins: 5,
    body: [
      { t: "p", text: "Somewhere near the main stage at Gage Park, a QR code is taped up where you might not notice it. There's another one by the food trucks. One at the baptism area. Six more are scattered through Vendor Row. Twelve in all — and every one of them is a light waiting to be found." },
      { t: "p", text: "It's called **the Light Hunt**, it's completely free, and it runs all weekend at [Jesus Festival Hamilton](https://www.jesusfestival.ca/), September 4–5, 2026." },
      { t: "h2", text: "How the Light Hunt works" },
      { t: "list", items: [
        "**Find a code.** Twelve Jesus Festival QR codes are hidden around Gage Park, near the places people gather — the stage, the big lawn, the kids zone, the food trucks, the baptism area, the info point, and all through the vendor market.",
        "**Scan it with your camera.** No app to install, nothing to sign up for. The lamp lights up on your phone instantly.",
        "**Collect the Scripture it carries.** Every light hands you a verse and a word of encouragement — twelve small moments with God scattered across a park.",
        "**Earn badges you can actually share.** First Light, Three Flames, Market Blessing, Light Bearer and more — nine in total, each one a real image your phone can post anywhere.",
      ] },
      { t: "p", text: "Every light you find also pours **Light Points** into [Revive the City](https://www.jesusfestival.app/revive-the-city) — the festival-wide game where the whole crowd's prayers, missions and discoveries add up to one shared story of a city coming alive. Find all twelve and you become a **Light Bearer**, with 2,500 points poured in and every badge unlocked." },
      { t: "h2", text: "It works with no signal — on purpose" },
      { t: "p", text: "Thousands of phones on one patch of grass means the network will crawl at exactly the moment you scan. The hunt is built for that: your lamps save on your phone the moment you scan, and your points reach the city as soon as you get a bar back. Nothing is lost, nobody waits on a spinner in a field." },
      { t: "h2", text: "Why half the lights are in the market" },
      { t: "p", text: "Six of the twelve lights sit in Vendor Row, and that's not an accident. Every booth at Jesus Festival is somebody's livelihood and somebody's offering — makers, ministries, and [Kingdom businesses](https://www.lionsdenalliance.com) who show up because they believe in what happens in this park. The hunt walks you right past them." },
      { t: "p", text: "So when a light sends you deep into the market: say hello. Ask the person at the table what they make. It costs you nothing, and it might be the best part of their day." },
      { t: "quote", text: "You are the light of the world. A town built on a hill cannot be hidden.", ref: "Matthew 5:14" },
      { t: "h2", text: "Tips from the people who hid them" },
      { t: "list", items: [
        "**Codes sit at chest height, out of glare.** If you can see the poster, your camera can read it — even creased or rained on.",
        "**Order doesn't matter.** Scanning any code starts your hunt. Station five first? That's your first light.",
        "**Bring the kids.** It's the best festival babysitter we know: a treasure hunt where every treasure is a verse.",
        "**Under an hour and a half is possible.** All twelve inside 90 minutes earns the Swift Light badge. You will not stroll.",
      ] },
      { t: "p", text: "The hunt lives in the [Jesus Festival app](https://www.jesusfestival.app/hunt) — which also carries the full schedule, the park map, and everything else you need for the weekend. It's free, it installs from the browser, and it works offline once it's loaded." },
      { t: "p", text: "Twelve lights. One park. Come find them all." },
    ],
    faqs: [
      { question: "What is the Light Hunt at Jesus Festival?", answer: "A free QR-code scavenger hunt across Gage Park during Jesus Festival Hamilton, September 4–5, 2026. Twelve codes are hidden around the park; scanning each one gives you a Bible verse, lights a lamp in the festival app, and unlocks shareable badges." },
      { question: "Does the Light Hunt cost anything or need an app?", answer: "No. It's completely free, there's nothing to install and nothing to sign up for — your phone's camera and browser are enough. Progress saves on your phone and works even with no signal." },
      { question: "What do you win in the Light Hunt?", answer: "Nine digital badges, each a shareable image — including Light Bearer for finding all twelve lights and Swift Light for finishing inside 90 minutes. Every find also adds Light Points to Revive the City, the festival's community game." },
      { question: "Where are the Light Hunt codes hidden?", answer: "Near the places people gather at Gage Park: the main stage, the big lawn, the kids zone, the food trucks, the baptism area, the info point — and six lights through Vendor Row, among the festival's makers and ministries." },
    ],
    related: ["JesusFestival.ca", "LoveonHamilton.com", "ThyKingdom.net"],
  },
  {
    slug: "wear-the-message",
    title: "What You Wear Can Start the Conversation",
    description:
      "Most Gospel conversations don't start with a sermon — they start with a question. On faith-worn-out-loud, the new Kingdom Shop, and the official Jesus Festival collection.",
    eyebrow: "Wear the message",
    emoji: "🛍️",
    date: "2026-08-05",
    readMins: 4,
    body: [
      { t: "p", text: "Here's a small evangelism secret nobody puts on conference slides: an enormous number of Gospel conversations don't start with an invitation or an argument. They start with a question. *\"What's your shirt about?\"*" },
      { t: "p", text: "A question is the easiest opening in the world, because the other person started it. No awkward pivot, no working up the nerve. They asked. You just answer honestly." },
      { t: "h2", text: "Faith was never meant to be invisible" },
      { t: "p", text: "There's a healthy caution in Christians who don't want faith to be a costume — Jesus had strong words for religion worn as performance. But there's a difference between performing and being unashamed. One is about looking impressive; the other is about being findable." },
      { t: "quote", text: "For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes.", ref: "Romans 1:16" },
      { t: "p", text: "A shirt won't save anyone. But it marks you as safe to ask — and in a lonely, quietly curious city, being safe to ask is no small ministry." },
      { t: "h2", text: "So we opened a shop" },
      { t: "p", text: "[The Kingdom Shop](https://thykingdom.shop) is the new home for apparel across the whole network — bold, well-made designs built to open conversations, from Seek First pieces to Love on Hamilton gear. And because you're reading this here: it carries the [official Jesus Festival collection](https://thykingdom.shop/collections/jesus-festival), including this year's festival tee." },
      { t: "p", text: "You can browse it right inside the app — open the [Festival Shop](https://www.jesusfestival.app/shop) — and checkout happens securely on the store." },
      { t: "h2", text: "Where the money goes" },
      { t: "p", text: "This is the part we care most about: the shop exists to fund the mission, not the other way around. Orders sow back into the Kingdom work behind this festival — the same heart as [SIX33 Outpost](https://www.six33outpost.com), and the same conviction the [Lions Den Alliance](https://www.lionsdenalliance.com) businesses carry: commerce, done right, is a Kingdom engine." },
      { t: "list", items: [
        "**Wear it to the festival.** Spot each other across Gage Park — one family, visibly.",
        "**Wear it after.** September 6 is when the shirt starts its real job.",
        "**Give one away.** A hoodie handed to a friend says more than most sermons.",
      ] },
      { t: "p", text: "And when someone does ask about your shirt — don't panic, don't preach. Just tell them what Jesus has actually done for you. That's the whole conversation. The shirt just opened the door." },
    ],
    related: ["ThyKingdom.Shop", "SIX33Outpost.com", "LionsDenAlliance.com"],
  },
  {
    slug: "why-a-free-festival",
    title: "Why We Give a Whole City a Free Festival",
    description:
      "No tickets, no barriers, no one turned away. The story behind why Jesus Festival Hamilton is completely free — and what that decision has cost and produced.",
    eyebrow: "The heart behind it",
    emoji: "🎪",
    date: "2026-08-02",
    readMins: 5,
    body: [
      { t: "p", text: "Every year someone asks the same question: *why free?* Running a two-day festival in a public park is not cheap. Stages, sound, security, insurance, kids zones — it all costs real money. Charging even ten dollars a head would cover a serious chunk of it." },
      { t: "p", text: "We don't, and we won't. Here's why." },
      { t: "h2", text: "Because the Gospel was free to us" },
      { t: "p", text: "The single most valuable thing any of us have ever received arrived with no invoice attached. Grace cost Jesus everything and cost us nothing. It would be strange to build an event around that message and then put a turnstile in front of it." },
      { t: "quote", text: "Freely you have received; freely give.", ref: "Matthew 10:8" },
      { t: "h2", text: "Because a ticket price sorts people" },
      { t: "p", text: "The moment there's a price, a sorting happens. The family stretching to the end of the month decides not to come. The teenager with no money doesn't ask. The person who's curious but not convinced isn't willing to gamble cash on it." },
      { t: "p", text: "Those are exactly the people we built this for. A free festival in a public park means the single mum, the skeptic, the guy walking his dog through Gage Park who had no idea this was on today — they can all just... walk in. That's the whole point." },
      { t: "h2", text: "Because it makes the Church visible in a good way" },
      { t: "p", text: "Cities have opinions about churches. Some of them are earned. A weekend where dozens of congregations pool their money and volunteers to give the city something beautiful — with nothing to sell — quietly rewrites some of those opinions." },
      { t: "p", text: "We've watched churches that had never spoken become friends over a shared tent. We've watched people who'd sworn off church sit on the grass through an entire worship set. That doesn't happen at a ticketed event." },
      { t: "h2", text: "How it actually gets paid for" },
      { t: "p", text: "By people. Partner churches, Kingdom businesses, and individuals who decide the city is worth it. If that stirs something in you, [giving toward the festival](https://www.jesusfestival.ca/donate) is the most direct way to keep a gate open for someone who couldn't otherwise walk through it." },
      { t: "p", text: "And if you're reading this from another city entirely, wondering whether something like this could happen where you live: it can. [JesusFestivalMovement.com](https://www.jesusfestivalmovement.com) exists for exactly that conversation." },
      { t: "p", text: "Come and see for yourself. September 4–5, Gage Park, Hamilton. Bring a friend. It won't cost either of you a thing." },
    ],
    related: ["JesusFestival.ca", "JesusFestivalMovement.com", "ThyKingdom.net"],
  },

  {
    slug: "you-already-know-your-mission-field",
    title: "You Already Know Your Mission Field",
    description:
      "Most of us are waiting for a calling to somewhere far away. Meanwhile God has already placed about a dozen people around you. Here's how to actually reach them.",
    eyebrow: "Everyday evangelism",
    emoji: "🧭",
    date: "2026-07-28",
    readMins: 6,
    body: [
      { t: "p", text: "There's a word the early Church used constantly that most of us have never heard: *oikos*. It's Greek for household — but not just the people under your roof. It meant your whole relational world: family, close friends, neighbours, the people you work with, the barista who knows your order." },
      { t: "p", text: "When the New Testament describes the Gospel spreading, it almost never spreads through strangers. It spreads through oikos. Cornelius gathers his household. The Philippian jailer's whole family believes. Andrew finds his brother first." },
      { t: "h2", text: "The problem with waiting for a calling" },
      { t: "p", text: "A lot of sincere Christians spend years waiting to be sent somewhere. Meanwhile there are roughly eight to fifteen people in their ordinary life who already trust them, already take their calls, and already notice how they handle a bad week." },
      { t: "p", text: "You will likely never have more spiritual credibility with anyone than you already have with those people. That's not a consolation prize. That's the assignment." },
      { t: "quote", text: "Go home to your own people and tell them how much the Lord has done for you.", ref: "Mark 5:19" },
      { t: "h2", text: "Three things that actually move the needle" },
      {
        t: "list",
        items: [
          "**Name them.** Vague intentions produce vague results. Write down the actual names. Most people are shocked how short and how obvious the list is.",
          "**Pray for them by name, consistently.** Not once in a burst of guilt — weekly, by name, for months. This is the part everyone skips and the part that changes everything.",
          "**Do one concrete kindness.** Not a sermon. A meal, a lift, an honest question, showing up when something hard happens. Love makes the message credible.",
        ],
      },
      { t: "h2", text: "A tool that makes it stick" },
      { t: "p", text: "We built [OikosMap.com](https://www.oikosmap.com) for exactly this, and it's completely free. You map the people already around you, see the whole picture on one page, and pray through it without needing to remember who you meant to pray for. It takes about five minutes to build and you'll use it for years." },
      { t: "p", text: "If you're the kind of person who ends up in a lot of real spiritual conversations and keeps losing the thread — who said what, who wanted a Bible, who you promised to follow up with — [KingdomBase.App](https://kingdombase.app) is built to hold that for you so nobody quietly falls through the cracks." },
      { t: "h2", text: "Then invite them to something easy" },
      { t: "p", text: "Here's why a free festival in a public park matters so much for this: it is one of the lowest-pressure invitations in existence. There's no service to sit through, no offering plate, no expectation. It's a park, some food trucks, and music." },
      { t: "p", text: "Your one person might never say yes to a church service. Most people will say yes to a free Saturday in the park with a friend. Start there." },
    ],
    related: ["OikosMap.com", "KingdomBase.App", "LoveonHamilton.com"],
  },

  {
    slug: "what-happens-after-you-say-yes",
    title: "What Happens After You Say Yes to Jesus",
    description:
      "Nobody hands you a manual the moment you believe. Here's an honest, gentle guide to the first weeks of following Jesus — what changes, what doesn't, and what to do next.",
    eyebrow: "New life",
    emoji: "🕊️",
    date: "2026-07-22",
    readMins: 6,
    body: [
      { t: "p", text: "Maybe it happened at a festival, in a car, in a hospital corridor, or lying awake at 3am. However it happened — you said yes to Jesus, and now you're wondering what you actually just signed up for." },
      { t: "p", text: "Nobody hands you a manual. So here's an honest one." },
      { t: "h2", text: "What actually changed" },
      { t: "p", text: "Something real and permanent happened, and it happened entirely on God's side of the ledger. You were forgiven. You were adopted. The Holy Spirit moved in. None of that is dependent on how spiritual you feel tomorrow morning." },
      { t: "quote", text: "Therefore, if anyone is in Christ, the new creation has come: the old has gone, the new is here!", ref: "2 Corinthians 5:17" },
      { t: "h2", text: "What probably didn't change (yet)" },
      { t: "p", text: "Your temper. Your anxiety. That habit. Your difficult family. Some people get a dramatic overnight rewiring — most don't, and that's not a sign anything went wrong." },
      { t: "p", text: "Sanctification is a slow, real, lifelong renovation, not a factory reset. The goal in week one is not to be impressive. It's to stay close." },
      { t: "h2", text: "Four things for the first month" },
      {
        t: "list",
        items: [
          "**Talk to God like a person, not a performance.** Out loud, in the car, in your own words. That's prayer. You don't need the vocabulary.",
          "**Read one Gospel.** Start with John. Ten minutes a day. Meet Jesus in his own words before anyone else explains him to you.",
          "**Tell one person.** Saying it out loud makes it real and gives someone the chance to walk with you.",
          "**Find actual people.** A church, a small group, one honest friend. Faith practised alone gets fragile fast.",
        ],
      },
      { t: "h2", text: "Where to go from here" },
      { t: "p", text: "[IAmReborn.net](https://www.iamreborn.net) was built for precisely this moment — the first days of new life, explained simply, without assuming you already know the language. If you're at the very start, begin there." },
      { t: "p", text: "When you're ready to go deeper into what it means to actually put the Kingdom first in ordinary life, [SeekFirst.World](https://www.seekfirst.world) picks up that thread." },
      { t: "p", text: "And if you're local, our [discipleship and partner churches](https://www.jesusfestival.ca/discipleship) are genuinely glad to meet you. You don't have to have it together to walk in. Nobody there does either." },
      { t: "p", text: "One last thing: you will have a bad week. It's coming. It is not evidence that this wasn't real. Keep showing up — He's not going anywhere." },
    ],
    related: ["IAmReborn.net", "SeekFirst.World", "KD-Ziedins.com"],
  },

  {
    slug: "how-to-love-your-city",
    title: "How to Actually Love a City",
    description:
      "Loving your city sounds noble and vague. Here's what it looks like in practice — small, repeatable, unglamorous things that genuinely change a neighbourhood.",
    eyebrow: "Loving your city",
    emoji: "🏙️",
    date: "2026-07-15",
    readMins: 5,
    body: [
      { t: "p", text: "\"Love your city\" is one of those phrases that sounds wonderful and means almost nothing until you make it specific. So let's make it specific." },
      { t: "h2", text: "Start by praying for one neighbourhood by name" },
      { t: "p", text: "Not \"the city\" — that's too big to feel. Pick a street, a school, a block you drive past. Pray for it by name for a month and watch how differently you start seeing it." },
      { t: "quote", text: "Seek the peace and prosperity of the city to which I have carried you… Pray to the Lord for it.", ref: "Jeremiah 29:7" },
      { t: "h2", text: "Then do the small, unglamorous things" },
      {
        t: "list",
        items: [
          "Learn the names of the people who work where you shop, and use them.",
          "Notice who's struggling on your street. Bring food before you're asked.",
          "Pick up litter in a park you didn't dirty.",
          "Show up to the neighbourhood thing you'd normally skip.",
          "Tip generously and be unreasonably kind to service staff.",
        ],
      },
      { t: "p", text: "None of this will trend. All of it is what a city actually feels when the Church is present." },
      { t: "h2", text: "Do it with other people" },
      { t: "p", text: "Loving a city alone burns you out in about six weeks. [LoveonHamilton.com](https://www.loveonhamilton.com) exists so that all this practical love happens together, all year — not just on festival weekend." },
      { t: "p", text: "If you're outside Hamilton, [LoveonTheWorld.com](https://www.loveontheworld.com) carries the same heart wherever you are, and [LoveonMission.world](https://www.loveonmission.world) maps where the Gospel is moving globally so you can pray with your eyes open." },
      { t: "h2", text: "And be ready for the hard days" },
      { t: "p", text: "Cities don't only need kindness — sometimes they need help fast. Floods, fires, storms. [KingdomResponse.com](https://www.kingdomresponse.com) mobilises churches to be first on the scene with real help and real hope when crisis hits. Loving a city means being there for its worst week, not just its best Saturday." },
      { t: "p", text: "Jesus Festival is two days a year. What we're actually after is a city that's different the other 363." },
    ],
    related: ["LoveonHamilton.com", "LoveonTheWorld.com", "LoveonMission.world", "KingdomResponse.com"],
  },

  {
    slug: "faith-at-work-kingdom-business",
    title: "Your Job Is Not a Distraction From Your Calling",
    description:
      "Most Christians spend more waking hours at work than anywhere else — and quietly assume it's spiritually neutral territory. It isn't.",
    eyebrow: "Faith at work",
    emoji: "🦁",
    date: "2026-07-08",
    readMins: 5,
    body: [
      { t: "p", text: "There's an unspoken hierarchy in a lot of churches. Pastors and missionaries do *ministry*. Everyone else has a *job* that pays for ministry. Work is the thing you get through so the real stuff can happen in the evenings." },
      { t: "p", text: "That idea is not in the Bible." },
      { t: "quote", text: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.", ref: "Colossians 3:23" },
      { t: "h2", text: "Where your life actually happens" },
      { t: "p", text: "You will spend something like 90,000 hours of your life at work. That's not the waiting room outside your calling — for most people it *is* the mission field, and it's full of people who will never attend a church service but who watch closely how you handle a deadline, a difficult client, or a mistake that was your fault." },
      { t: "h2", text: "What it looks like on a Tuesday" },
      {
        t: "list",
        items: [
          "**Excellence as worship.** Sloppy work with a fish on the invoice damages the name you're trying to honour.",
          "**Integrity when it costs.** The quiet decisions nobody would ever catch are the ones that build actual credibility.",
          "**Treating people like people.** Especially the ones who can do nothing for you.",
          "**Generosity with what it produces.** Profit is a tool. Kingdom business owners fund things that could never fund themselves.",
        ],
      },
      { t: "h2", text: "Don't do it alone" },
      { t: "p", text: "Running a business with Kingdom conviction is lonely if nobody around you shares it. [LionsDenAlliance.com](https://www.lionsdenalliance.com) is an alliance of Christian business owners who refuse to separate Sunday from Monday — and much of what funds a free festival comes from exactly these people." },
      { t: "p", text: "A few examples of what this looks like when it's built on purpose: [SIX33Outpost.com](https://www.six33outpost.com) makes apparel designed to start conversations before you say a word. [SIX33Legends.com](https://www.six33legends.com) builds cinematic storytelling that makes courage and faith feel as epic as they actually are. And [TaskSimply.com](https://www.tasksimply.com) is a quieter kind of Kingdom tool — tasks, teams and budgets in one calm place, because stewarding your days well is genuinely spiritual work." },
      { t: "p", text: "If you want the longer version of the thinking behind building Kingdom things in the everyday world, [DanielZiedins.com](https://www.danielziedins.com) is where that's written out." },
      { t: "p", text: "Your work is not a distraction from your calling. Handled well, it may be the largest part of it." },
    ],
    related: ["LionsDenAlliance.com", "SIX33Outpost.com", "SIX33Legends.com", "TaskSimply.com", "DanielZiedins.com"],
  },

  {
    slug: "one-invitation-changes-everything",
    title: "The Most Underrated Thing You Can Do This Year",
    description:
      "Not a program. Not a platform. Just one honest invitation to one person — and why it's still how almost everyone finds their way in.",
    eyebrow: "The invitation",
    emoji: "🤝",
    date: "2026-07-01",
    readMins: 4,
    body: [
      { t: "p", text: "Ask around a room of Christians how they first came to faith and you'll rarely hear \"an advert\" or \"an algorithm.\" You'll hear a name. A friend who invited them. A coworker who kept being kind. A grandmother who prayed for two decades." },
      { t: "p", text: "It's almost always a person. It's almost always an invitation." },
      { t: "h2", text: "Why we don't do it" },
      { t: "p", text: "Mostly fear — of being weird, of damaging a friendship, of not having answers. Which is understandable, and also mostly imaginary. You're not asking someone to sign a doctrinal statement. You're asking if they want to come to a thing." },
      { t: "quote", text: "Go out to the roads and country lanes and compel them to come in, so that my house will be full.", ref: "Luke 14:23" },
      { t: "h2", text: "Make it as easy as possible to say yes" },
      { t: "p", text: "This is exactly why a free, outdoor, no-strings festival is such a useful front door. There's no service to endure, no offering, no commitment. It's a park on a Saturday with food trucks and music." },
      { t: "p", text: "The app makes this almost effortless — open [the invite card](https://www.jesusfestival.app) and it generates a shareable image with the date and details already on it. One tap, one text, done." },
      { t: "h2", text: "Then just be normal" },
      { t: "p", text: "Go with them. Buy them a coffee. Don't over-explain, don't monitor their reaction during worship, don't debrief them in the car like an exit interview. Let God do God's part." },
      { t: "p", text: "You are not responsible for the outcome. You're responsible for the invitation." },
      { t: "p", text: "So — who's your one? You almost certainly thought of someone in the first ten seconds of reading this. That's not random. Text them today." },
    ],
    related: ["JesusFestival.ca", "OikosMap.com", "IAmReborn.net"],
  },
];

export const postBySlug = (slug: string) => BLOG_POSTS.find((p) => p.slug === slug);

/** Newest first — the order the blog index and sitemap use. */
export const sortedPosts = () => [...BLOG_POSTS].sort((a, b) => b.date.localeCompare(a.date));
